// build.js — runs during Cloudflare Pages build
// Reads the resvg WASM binary, base64-encodes it,
// and writes it as a JS module that og.js can import.
const fs   = require('fs');
const path = require('path');

const wasmPath = path.join(__dirname, 'node_modules/@resvg/resvg-wasm/index_bg.wasm');
const outPath  = path.join(__dirname, 'functions/api/_resvg_wasm_b64.js');

const wasmBuf = fs.readFileSync(wasmPath);
const b64     = wasmBuf.toString('base64');

const out = `// AUTO-GENERATED by build.js — do not edit manually
// Contains the resvg-wasm binary as base64, embedded at build time.
export const RESVG_WASM_B64 = '${b64}';
`;

fs.writeFileSync(outPath, out, 'utf8');
console.log('build.js: wrote _resvg_wasm_b64.js (' + Math.round(b64.length / 1024) + ' KB)');
